ALTER TABLE `char` CHANGE `str` `str` TINYINT( 3 ) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `char` CHANGE `dex` `dex` TINYINT( 3 ) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `char` CHANGE `intel` `intel` TINYINT( 3 ) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `char` CHANGE `con` `con` TINYINT( 3 ) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `char` CHANGE `luk` `luk` TINYINT( 3 ) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE `char` CHANGE `stpoints` `stpoints` TINYINT( 3 ) UNSIGNED NOT NULL DEFAULT '0'