DROP TABLE IF EXISTS `market`;
CREATE TABLE `market` (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`item_id` INT UNSIGNED NOT NULL ,
`item_type` TINYINT UNSIGNED NOT NULL ,
`item_clv` TINYINT UNSIGNED NOT NULL ,
`item_stack` TINYINT UNSIGNED NOT NULL ,
`item_durability` SMALLINT UNSIGNED NOT NULL ,
`owner` VARCHAR( 40 ) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
`price` INT UNSIGNED NOT NULL ,
`expire` VARCHAR( 40 ) NOT NULL ,
`comment` VARCHAR( 1024 ) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL 
) ENGINE = innodb DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;