CREATE TABLE `mail` (
`mailID` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`sender` VARCHAR( 34 ) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
`receiver` VARCHAR( 34 ) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
`topic` VARCHAR( 40 ) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
`date` VARCHAR( 30 ) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
`content` VARCHAR( 402 ) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
`read` TINYINT UNSIGNED NOT NULL ,
`valid` TINYINT UNSIGNED NOT NULL ,
`zeny` INT UNSIGNED NOT NULL ,
`itemID` INT UNSIGNED NOT NULL ,
`creator` VARCHAR( 36 ) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL ,
`stack` TINYINT UNSIGNED NOT NULL ,
`durability` SMALLINT UNSIGNED NOT NULL
) ENGINE = innodb DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;