CREATE TABLE `weapon` (
`charID` INT UNSIGNED NOT NULL ,
`name` VARCHAR( 24 ) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL ,
`level` TINYINT UNSIGNED NOT NULL ,
`type` TINYINT UNSIGNED NOT NULL ,
`augeSkillID` INT UNSIGNED NOT NULL ,
`exp` INT UNSIGNED NOT NULL ,
`durability` SMALLINT UNSIGNED NOT NULL ,
`U1` TINYINT UNSIGNED NOT NULL ,
`active` TINYINT UNSIGNED NOT NULL 
) ENGINE = innodb;
