CREATE TABLE `skills` (
`charID` INT UNSIGNED NOT NULL ,
`type` TINYINT UNSIGNED NOT NULL ,
`skillID` INT UNSIGNED NOT NULL,
`exp` INT UNSIGNED NOT NULL
) ENGINE = innodb CHARACTER SET utf8 COLLATE utf8_unicode_ci;
