ALTER TABLE `char` ADD `Scenario` INT UNSIGNED NOT NULL DEFAULT '0' AFTER `party` ;
CREATE TABLE `MapInfo` (
`charID` INT UNSIGNED NOT NULL ,
`map` TINYINT UNSIGNED NOT NULL ,
`value` TINYINT UNSIGNED NOT NULL
) ENGINE = innodb;