pageinfo = [[1183502245,5544],
	[1196262619,7816],
	[1183502391,2728],
	[1183499469,16691],
	[1183499465,9920],
	[1184001057,4135],
	[1196262839,3885],
	[1196262927,3118],
	[1196263015,2437],
	[1196263163,4761],
	[1183502977,2902],
	[1196263505,5954],
	[1183503045,2577],
	[1183495489,1719],
	[1183503109,2580],
	[1183500071,5561],
	[1196263631,3815],
	[1196263601,2898],
	[1183503143,2747],
	[1183503177,2568],
	[1183503231,2582],
	[1196265161,1711],
	[1183500341,24101],
	[1196264263,1751],
	[1196264145,5543],
	[1196264395,14808],
	[1183501833,17525],
	[1196263791,2701],
	[1183499019,1774],
	[1196264789,2196],
	[1196263825,2777],
	[1183503293,2709],
	[1183503333,2409],
	[1183503461,2616],
	[1183503493,2567],
	[1196264325,14057],
	[1196264363,28775],
	[1183503523,2377],
	[1183505625,1729],
	[1183496705,5440],
	[1183503559,3270],
	[1183503613,2521],
	[1183503679,2609],
	[1183503741,2922],
	[1183503769,3793],
	[1196264227,2944],
	[1183499477,3849],
	[1183805429,1745],
	[1183503811,2738],
	[1183503871,2569],
	[1196263917,2423],
	[1183503993,2935],
	[1183504057,3724],
	[1183543259,3314],
	[1196264451,3807]];
pagedata = [ ["./addbutton.htm","AddButton","﻿AddButton Top Previous Next This method is used for adding a function to this npc AddButton method has these three variant: public void AddButton...",""],
["./addenemyinfo.htm","AddEnemyInfo","﻿AddEnemyInfo Top Previous Next This function is used for adding enemy that should be defeated in a quest. public void AddEnemyInfo(uint QID, uint...",""],
["./addgoods.htm","AddGoods","﻿AddGoods Top Previous Next public void AddGoods(int id) this method is used to add goods to a NPC shop/book store int id: ID of a item from itemDB ",""],
["./addition.htm","Addition","﻿Addition Top Previous Next This file is used for defining bonuses of items/skills example: &#60;addition&#62; &#60;id&#62;601&#60;/id&#62; &#60;Unknown1&#62;1&#60;/Unknown1&#62; &#60;Unknow...",""],
["./addition_bonus.htm","Addition Bonus","﻿Addition Bonus Top Previous Next These are possible bonus for current version of Saga: PhysicalATKMin RangedATKMin PhysicalATKMax RangedATKMax, P...",""],
["./addmobloot.htm","AddMobLoot","﻿AddMobLoot Top Previous Next public void AddMobLoot(uint mobid, uint QID, uint SID , int ItemID, uint rate) this method is used for adding a temp...",""],
["./addpersonalquest.htm","AddPersonalQuest","﻿AddPersonalQuest Top Previous Next this method is used for adding a personal quest to a npc, analog to AddQuest public void AddPersonalQuest(uint...",""],
["./addpersonalqueststep.htm","AddPersonalQuestStep","﻿AddPersonalQuestStep Top Previous Next Add a QuestStep to a personal quest public void AddPersonalQuestStep(uint QID, uint SID, StepStatus s) see...",""],
["./addquest.htm","AddQuest","﻿AddQuest Top Previous Next public void AddQuest(uint id) Add a quest to a npc. usually used for mission boards ",""],
["./addquestitem.htm","AddQuestItem","﻿AddQuestItem Top Previous Next public void AddQuestItem( uint QID, uint SID, uint itemID, byte ammount ) public void AddQuestItem(uint QID, uint ...",""],
["./addqueststep.htm","AddQuestStep","﻿AddQuestStep Top Previous Next public void AddQuestStep(uint QID, uint SID, StepStatus s) Add a Quest Step trigger to a npc ",""],
["./addrewardchoice.htm","AddRewardChoice","﻿AddRewardChoice Top Previous Next public void AddRewardChoice(ActorPC pc, int itemid) this method is used for quests, which player should choose ...",""],
["./addstep.htm","AddStep","﻿AddStep Top Previous Next public void AddStep(uint QuestID, uint StepID) Add one new step to a quest. ",""],
["./chapter_2.htm","Quick Start","﻿Quick Start Top Previous Next Enter topic text here. ",""],
["./countitem.htm","CountItem","﻿CountItem Top Previous Next public byte CountItem(ActorPC pc, int ItemID) returns the amount of a item. ",""],
["./exp.htm","EXP","﻿EXP Top Previous Next exp.xml is used for leveling structure: &#60;level&#62; &#60;lv&#62;1&#60;/lv&#62; &#60;c&#62;0&#60;/c&#62; &#60;j&#62;0&#60;/j&#62; &#60;w&#62;0&#60;/w&#62; &#60;statusPoint&#62;0&#60;/statusPoint&#62; &#60;/level&#62;...",""],
["./getactivequest.htm","GetActiveQuest","﻿GetActiveQuest Top Previous Next Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam velit risus, placerat et, rutrum nec, condimen...",""],
["./getqueststepstatus.htm","GetQuestStepStatus","﻿GetQuestStepStatus Top Previous Next public StepStatus GetQuestStepStatus( ActorPC pc, uint QID, uint SID ) Get the status of a certain quest&#38;step ",""],
["./giveitem.htm","GiveItem","﻿GiveItem Top Previous Next public void GiveItem(Actor dActor, int itemID, byte ammount) Give item to an actor ",""],
["./givezeny.htm","GiveZeny","﻿GiveZeny Top Previous Next public void GiveZeny(ActorPC pc, uint amount) Give money to a player. ",""],
["./ifgotquest.htm","IfGotQuest","﻿IfGotQuest Top Previous Next public bool IfGotQuest(ActorPC pc, uint id) Check if a player has got a Quest. ",""],
["./introduction.htm","Introduction","﻿Introduction Top Next This is the documentation for Saga based on revision:593 ",""],
["./item.htm","Item","﻿Item Top Previous Next item.xml is used for defining items. structure: &#60;item&#62; &#60;id&#62;1&#60;/id&#62; &#60;mesh&#62;0&#60;/mesh&#62; &#60;icon&#62;100000&#60;/icon&#62; &#60;unknown5&#62;0&#60;/unknown5...",""],
["./mailbox.htm","MailBox","﻿MailBox Top Previous Next Inherited from Npc class, implements a mailbox. Has no extended method. ",""],
["./mapitem.htm","MapItem","﻿MapItem Top Previous Next It&#39;s a sub class of Npc, it has all methods which are provided by Npc class. And has following extended methods: public...",""],
["./new_topic.htm","SagaGateway","﻿SagaGateway Top Previous Next The gateway server is the simplest component of Saga, so is its configuration. &#60;?xml version=\"1.0\" encoding=\"utf-8\"...",""],
["./npc.htm","Npc","﻿Npc Top Previous Next Npc class provides all needed methods for npcs. Example code: using System; using System.Collections.Generic; using SagaMap...",""],
["./npcspeech.htm","NPCSpeech","﻿NPCSpeech Top Previous Next public void NPCSpeech(ActorPC pc, uint script) make a npc say something in the chatting bubble. ",""],
["./overview.htm","Overview","﻿Overview Top Previous Next This chapter tells you the function and structure of the DB files under DB folder. ",""],
["./overview2.htm","Overview","﻿Overview Top Previous Next This chapter tells you everything needed for scripting in Saga.(For revision: 593) scripts are stored under scripts\\np...",""],
["./personalqueststart.htm","PersonalQuestStart","﻿PersonalQuestStart Top Previous Next public void PersonalQuestStart(ActorPC pc) start a personal quest usage is the same as QuestStart ",""],
["./questcompleted.htm","QuestCompleted","﻿QuestCompleted Top Previous Next public void QuestCompleted(ActorPC pc, uint QID) Indicate a player, that a certain Quest is completed. ",""],
["./queststart.htm","QuestStart","﻿QuestStart Top Previous Next public void QuestStart(ActorPC pc) Start a new quest ",""],
["./removenavpoint.htm","RemoveNavPoint","﻿RemoveNavPoint Top Previous Next public void RemoveNavPoint(ActorPC pc, uint QID) Remove all navigation points of a certain Quest ",""],
["./removequest.htm","RemoveQuest","﻿RemoveQuest Top Previous Next public void RemoveQuest(ActorPC pc, uint QID) Remove a Quest ",""],
["./sagalogin.htm","SagaLogin","﻿SagaLogin Top Previous Next Contents of login.config: &#60;?xml version=\"1.0\"?&#62; &#60;SagaLogin&#62; &#60;host&#62;127.0.0.1&#60;/host&#62; &#60;!-- address of SQL/db4o server or...",""],
["./sagamap.htm","SagaMap","﻿SagaMap Top Previous Next Contents of map.config: &#60;?xml version=\"1.0\"?&#62; &#60;SagaMap&#62; &#60;host&#62;127.0.0.1&#60;/host&#62; &#60;port&#62;3011&#60;/port&#62; &#60;?IP address of SQL/db...",""],
["./say.htm","Say","﻿Say Top Previous Next public void Say(string sentence) Say something ",""],
["./scripting_commands.htm","Scripting Commands","﻿Scripting Commands Top Previous Next Enter topic text here. ",""],
["./second_topic.htm","License","﻿License Top Previous Next Saga is Licensed under Creative Commons Attribution-NonCommerial-ShareAlike 3.0 License You are free: • to Share — to c...",""],
["./sendnavpoint.htm","SendNavPoint","﻿SendNavPoint Top Previous Next public void SendNavPoint(ActorPC pc,uint QID, uint npcType, float x, float y, float z) Send a navigation point of ...",""],
["./sendquestlist.htm","SendQuestList","﻿SendQuestList Top Previous Next public void SendQuestList(ActorPC pc) Send the quest list of current Mission board ",""],
["./setreward.htm","SetReward","﻿SetReward Top Previous Next public void SetReward(ActorPC pc, rewardfunc func) Set a reward handling method for a certain player ",""],
["./setsavepoint.htm","SetSavePoint","﻿SetSavePoint Top Previous Next public void SetSavePoint(byte map,float x,float y, float z) Set the saving point for this Kafra ",""],
["./setscript.htm","SetScript","﻿SetScript Top Previous Next Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam velit risus, placerat et, rutrum nec, condimentum a...",""],
["./ship.htm","Ship","﻿Ship Top Previous Next Inherited from Npc class, which represents a ship, has one extended method:. public void Init(byte orimapid,float dstx,flo...",""],
["./starting_the_server.htm","Starting the server","﻿Starting the server Top Previous Next 1. Edit the configuration files(Dat is the default DB mode, see Confuguration for detail) 2. Setup the MySQ...",""],
["./sub_chapter_2_1.htm","Configuration","﻿Configuration Top Previous Next This Chapter tells you how to configure Saga. ",""],
["./takeitem.htm","TakeItem","﻿TakeItem Top Previous Next public void TakeItem(ActorPC pc, int itemID, byte ammount) Take item from a player ",""],
["./takezeny.htm","TakeZeny","﻿TakeZeny Top Previous Next public void TakeZeny(ActorPC pc, uint amount) Take money from a player ",""],
["./updateicon.htm","UpdateIcon","﻿UpdateIcon Top Previous Next public void UpdateIcon(ActorPC pc) update the icon shown above of a npc ",""],
["./updatequeststep.htm","UpdateQuest","﻿UpdateQuest Top Previous Next public void UpdateQuest(ActorPC pc, uint QID, uint SID, StepStatus s) Update the status of a certain quest step ",""],
["./warp.htm","Warp","﻿Warp Top Previous public void Warp(ActorPC pc, byte mapid) public void Warp(ActorPC pc, byte mapid, float x, float y, float z) Warp a player to a...",""],
["./welcome_topic.htm","Welcome","﻿Welcome Top Previous Next Welcome to the Saga RO2 server software. As some of you might know, Gravity is releasing a sequel to Ragnarok Online an...",""],
["./world.htm","World","﻿World Top Previous Next Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam velit risus, placerat et, rutrum nec, condimentum at, l...",""]];
